# エラー処理

## TODO
- 「エラー処理とは」がエラー処理の説明になってないな。
- Swift のエラー型には ErrorType と Error がある。前者は Swift2 まで、Swift3 からは Error
- Error はプロトコルで NSError のように domain や code は持っていない。NSError の domain, code を Error 型から取り出すには `_domain`、`_code` プロパティを使う。
	https://qiita.com/kunichiko/items/e5405b9edbea8fed86d2


## 目次
- エラー処理とは
- try/try?/try!
- do-catch 文
- defer 文
- rethrows


## エラー処理とは
- エラーを投げるには <u>throw 文</u>を使う。
	```Swift
	throw <ErrorType プロトコルを実装したインスタンス>
	```
- エラーを投げる関数には <u>throws キーワード</u>を付ける。
	```Swift
	func hoge() throws -> String
	```
- エラーを投げる関数の呼び出しは <u>try 演算子</u>を付けて行わなければいけない。付けないとビルドエラー。
	```Swift
	try hoge()
	```
- エラーは Java の例外と同じように<u>呼び出し階層の上に伝搬</u>していく。
- エラーをキャッチしたい場合は <u>do-catch 文</u>を使う。

<small>**例.** エラーを投げる関数の定義と呼び出し</small>
```Swift
class MyError : ErrorType {
}

func foo(i: Int) throws {
    if (i < 0) {
        throw MyError()
    }
    print(i)
}

try foo(3)
```


## try/try?/try!
- try 演算子には「?」や「!」を付けて呼び出すことができる。それぞれの挙動は下記。

構文|foo()がエラーを投げた場合|foo() が正常終了した場合
:--|:--|:--
try foo()|エラーが伝搬|値が返る
try? foo()|nil が返る|値が返る（Optional 型になる）
try! foo()|実行時エラーが発生しプログラムが停止<br>エラーの伝搬はない|値が返る

```Swift
let s1: String = try hoge(1)
let s2: String? = try? hoge(1)
let s3: String = try! hoge(1)
```

## do-catch 文
```Swift
// 文法
do {
	// ここで try でメソッド呼び出し
} catch パターン {
	// エラーがパターンに一致した際の処理
} catch パターン where節 {
	// エラーがパターンと where に一致した際の処理
} catch {
	// エラーが上の catch で一致しなかった場合の処理
}
```

- パターンも where も指定しない catch 節の中ではエラーのインスタンスを「error」という変数で参照できる。<br>
	<font color="red">※ パターンした場合でエラーインスタンス参照するには？</font>
	```Swift
	do {
	    try hoge(-1)	// MyError を投げる
	} catch {
	    print("error=" + String(error))	//=> "error=MyError"
	}
	```

<small>**例.** do-catch の catch を使う例</small>
```Swift
class MyError : ErrorType {

}

func hoge(i: Int) throws -> String {
    if (i < 0) {
        throw MyError()
    }
    return "hoge" + String(i)
}

var num = 5
do {
    try hoge(0)
} catch is MyError where num > 3 {
    print("error")
} catch {
    print("other")
}
```

## defer 文
<font color="gray"><small>defer の定義</small></font>
```Swift
defer {
    // 任意の処理
}
```

- defer はコードブロック内の直下に書いて、その<u>ブロックから処理が抜けるタイミングで処理を実行</u>させられる。
- for や while の場合は<u>繰り返しごとにブロックから抜けた使い</u>になる。
- defer はそのブロック内で経由した <u>defer 文が経由した順とは逆順に実行</u>される。
- defer 内の変数はブロックが実行される時の値が使われる。（クロージャのような変数のキャプチャはない）

<small>**例1.** defer 文の実行順と変数の扱いの例</small>
```Swift
var a = 0

func foo() {
    var b = 0
    defer {
        a += 1
        b += 1
        print("[1] a=\(a) b=\(b)")
    }

    defer  {
        a += 1
        b += 1
        print("[2] a=\(a) b=\(b)")
    }
}

foo()
print("[3] a=\(a)")
```
*結果*
```text
[2] a=1 b=1
[1] a=2 b=2
[3] a=2
```

<small>**例2.** defer が直上のブロックを抜けると呼ばれる例</small>
```Swift
if true {
    defer {
        print("defer1")
    }
    if true {
        defer {
            print("defer2")
        }
        print("if2")
    }
    print("if1")
}
```
*結果*
```text
if2
defer2
if1
defer1
```


## rethrows
- パラメータの関数型インスタンス内のエラーの `throws` を高階関数側のエラーとして `throws` させるというもの。
	- パラメータの関数インスタンスが `throws` しない宣言なら、高階関数も `throws` なしの関数として扱う。→ 高階関数の呼び出しに `try` 必要
	- パラメータの関数インスタンスが `throws` する宣言なら、高階関数も `throws` ありの関数として扱う。→ 高階関数の呼び出しに `try` 不要
		- 関数側が投げる場合のみ、`try` 書けばよいところが便利なとこ。`rethrows` でなく `throws` だと毎回 `try` 呼び出ししないといけない。
- 関数インスタンス以外の部分でエラー投げる場合は高階関数を `throws` にして毎回 `try` 書くようにする。
	```Swift
	func foo(n: Int, handler: () throws -> Void) throws {
	    try handler()

	    if (n < 0) {
	        throw NSError()  // 高階関数内でエラー投げる場合は、rethrows ではなく throws にする
	    }
	}
	```

> - 「() throws -> T」という型には「() -> T」のような例外定義の無いものも指定できる。
> - 「高階関数」とは関数を引数、または戻り値にもつ関数。


```Swift
func foo(handler: () throws -> Void) rethrows {
    try handler()
}

// パラメータの関数インスタンスが throws する宣言の場合 → try foo()
try foo { () throws -> Void in
    print("a")
    throw NSError()
}

// パラメータの関数インスタンスが throws しない宣言の場合 → foo()
foo { () -> Void in
    print("b")
}

// 型推論で throws するとされた場合 → try foo()
try foo {
    throw NSError()
}
````
